name: E2E workflow

on:
  push:
    branches:
      - "*"

jobs:
  e2e:
    name: E2E tests
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged


    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      - name: Build API image
        run: |
          cd src/api 
          docker build . --file Dockerfile --tag api

      - name: Build Web image
        run: |
          cd src/web 
          docker build . --file Dockerfile --tag web

      - name: Start all services
        run: |
          cd src/web
          docker-compose up -d

      - name: Run E2E tests
        run: |
          cd src/web
          npm i -D
          npx playwright install chromium --with-deps
          npm run e2e

      - name: Shut down and clean up
        run: |
          cd src/web
          docker-compose down