name: E2E workflow

on:
  push:
    branches:
      - "*"

jobs:
  e2e:
    name: E2E tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Build API image
        run: docker build . --file src/api/Dockerfile --tag api

      - name: Build Web image
        run: docker build . --file src/web/Dockerfile --tag web

      - name: Start all services
        run: |
          cd src/web
          docker-compose up -d

      - name: Run E2E tests
        run: |
          cd src/web
          npm i -D && npm run e2e
