# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - "*"

env:
  DOCKER_IMAGE_NAME: project-image

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests:
    name: Running tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies and tests
        run: |
          cd src/api
          python -m pip install "poetry==1.8.1"
          poetry install --no-root
          ls -a
