name: Web workflow

on:
  push:
    branches:
      - "*"

env:
  API_URL: http://localhost:8000
  WEB_APP_PORT: 3000


jobs:
  web:
    name: Web part
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '22.x'

      - name: Build
        run: |
          cd src/web
          npm install
          npm run build
          
