name: Web workflow

on:
  push:
    branches:
      - "*"

env:
  API_URL: http://localhost:8000
  WEB_APP_PORT: 3000


jobs:
  web:
    name: Web part
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Build project image
        run: |
          cd src/web
          docker build . --file Dockerfile --tag web

      - name: Run service
        run: |
          cd src/web
          docker run -p 3000:3000 --name web -d web:latest

      - name: Run tests
        run: |
          cd src/web
          npm i -D 
          npm run tests:mocked
          
